#!/usr/bin/env bash

# Get the commit message file path
commit_msg_filepath="$1"

# Read the commit message
commit_msg=$(cat "$commit_msg_filepath")

# Check if the commit message matches the required format
# the format is [action]: description
if ! [[ "$commit_msg" =~ ^\[.*\]: ]]; then
    echo "Your commit message does not follow the standard"
    exit 1
fi
